set check_function_bodies = off;

create extension if not exists pgcrypto with schema extensions;

do $$
begin
  create type public.admin_role as enum ('admin', 'staff');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.booking_status as enum (
    'pending_payment',
    'confirmed',
    'rejected',
    'cancelled',
    'expired'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.payment_amount_type as enum ('deposit_50', 'total');
exception
  when duplicate_object then null;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null default 'staff',
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_admin_profiles_updated_at on public.admin_profiles;
create trigger set_admin_profiles_updated_at
before update on public.admin_profiles
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.admin_profiles
    where id = auth.uid()
      and is_active = true
      and role in ('admin', 'staff')
  );
$$;

create or replace function public.is_owner_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.admin_profiles
    where id = auth.uid()
      and is_active = true
      and role = 'admin'
  );
$$;

do $$
declare
  seed_admin_id uuid := '9d21e92d-6d34-4a68-9c18-e1e5c6902d5a';
  seed_admin_email text := 'eurekaAdmin@gmail.com';
begin
  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    created_at,
    updated_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    is_sso_user,
    is_anonymous,
    confirmation_token,
    recovery_token,
    email_change_token_new,
    email_change
  )
  values (
    '00000000-0000-0000-0000-000000000000',
    seed_admin_id,
    'authenticated',
    'authenticated',
    seed_admin_email,
    extensions.crypt('Eurekaadmin799', extensions.gen_salt('bf')),
    now(),
    now(),
    now(),
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    '{}'::jsonb,
    false,
    false,
    false,
    '',
    '',
    '',
    ''
  )
  on conflict (id) do update
  set email = excluded.email,
      encrypted_password = excluded.encrypted_password,
      email_confirmed_at = excluded.email_confirmed_at,
      updated_at = now(),
      raw_app_meta_data = excluded.raw_app_meta_data;

  insert into auth.identities (
    id,
    user_id,
    provider_id,
    provider,
    identity_data,
    last_sign_in_at,
    created_at,
    updated_at
  )
  values (
    seed_admin_id,
    seed_admin_id,
    seed_admin_email,
    'email',
    jsonb_build_object(
      'sub', seed_admin_id::text,
      'email', seed_admin_email,
      'email_verified', true,
      'phone_verified', false
    ),
    now(),
    now(),
    now()
  )
  on conflict (provider_id, provider) do update
  set user_id = excluded.user_id,
      identity_data = excluded.identity_data,
      updated_at = now();

  insert into public.admin_profiles (id, role, display_name, is_active)
  values (seed_admin_id, 'admin', 'Admin Eureka', true)
  on conflict (id) do update
  set role = 'admin',
      display_name = excluded.display_name,
      is_active = true,
      updated_at = now();
end $$;

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  phone text not null,
  email text not null,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_contacts_updated_at on public.contacts;
create trigger set_contacts_updated_at
before update on public.contacts
for each row execute function public.set_updated_at();

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

create table if not exists public.booking_duration_prices (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  duration_minutes integer not null unique check (duration_minutes > 0),
  price numeric(10, 2) not null check (price >= 0),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists booking_duration_prices_active_order_idx
on public.booking_duration_prices (is_active, sort_order, duration_minutes);

drop trigger if exists set_booking_duration_prices_updated_at on public.booking_duration_prices;
create trigger set_booking_duration_prices_updated_at
before update on public.booking_duration_prices
for each row execute function public.set_updated_at();

create table if not exists public.hero_slides (
  id uuid primary key default gen_random_uuid(),
  title text,
  subtitle text,
  image_path text not null,
  alt_text text not null default 'Imagen de Eureka',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hero_slides_active_order_idx
on public.hero_slides (is_active, sort_order, created_at);

drop trigger if exists set_hero_slides_updated_at on public.hero_slides;
create trigger set_hero_slides_updated_at
before update on public.hero_slides
for each row execute function public.set_updated_at();

create table if not exists public.novelty_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  price numeric(10, 2),
  image_path text not null,
  badge text not null default 'Promo destacada',
  sort_order integer not null default 0,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists novelty_items_active_order_idx
on public.novelty_items (is_active, sort_order, created_at);

drop trigger if exists set_novelty_items_updated_at on public.novelty_items;
create trigger set_novelty_items_updated_at
before update on public.novelty_items
for each row execute function public.set_updated_at();

create table if not exists public.pedidosya_promos (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  image_path text not null,
  cta_label text not null default 'Pedir en PedidosYa',
  cta_url text not null,
  points text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_pedidosya_promos_updated_at on public.pedidosya_promos;
create trigger set_pedidosya_promos_updated_at
before update on public.pedidosya_promos
for each row execute function public.set_updated_at();

create table if not exists public.payment_qrs (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  image_path text not null,
  instructions text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_payment_qrs_updated_at on public.payment_qrs;
create trigger set_payment_qrs_updated_at
before update on public.payment_qrs
for each row execute function public.set_updated_at();

create table if not exists public.booking_availability_rules (
  id uuid primary key default gen_random_uuid(),
  weekday smallint not null check (weekday between 0 and 6),
  opens_at time not null,
  closes_at time not null,
  is_open boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_availability_valid_hours check (opens_at < closes_at)
);

create unique index if not exists booking_availability_rules_weekday_idx
on public.booking_availability_rules (weekday);

drop trigger if exists set_booking_availability_rules_updated_at on public.booking_availability_rules;
create trigger set_booking_availability_rules_updated_at
before update on public.booking_availability_rules
for each row execute function public.set_updated_at();

create table if not exists public.booking_blackouts (
  id uuid primary key default gen_random_uuid(),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_blackouts_valid_range check (starts_at < ends_at)
);

drop trigger if exists set_booking_blackouts_updated_at on public.booking_blackouts;
create trigger set_booking_blackouts_updated_at
before update on public.booking_blackouts
for each row execute function public.set_updated_at();

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  reservation_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)),
  full_name text not null,
  phone text not null,
  national_id text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  party_size integer not null default 1 check (party_size > 0),
  status public.booking_status not null default 'pending_payment',
  payment_type public.payment_amount_type not null default 'deposit_50',
  total_amount numeric(10, 2) not null default 0 check (total_amount >= 0),
  amount_due numeric(10, 2) not null check (amount_due >= 0),
  payment_qr_id uuid references public.payment_qrs(id) on delete set null,
  payment_receipt_path text,
  payment_reference text,
  admin_notes text,
  change_used boolean not null default false,
  change_expires_at timestamptz not null,
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  confirmed_at timestamptz,
  rejected_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_valid_range check (starts_at < ends_at)
);

create index if not exists bookings_calendar_idx
on public.bookings (starts_at, ends_at, status);

create index if not exists bookings_phone_idx
on public.bookings (phone);

drop trigger if exists set_bookings_updated_at on public.bookings;
create trigger set_bookings_updated_at
before update on public.bookings
for each row execute function public.set_updated_at();

create table if not exists public.notification_events (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid references public.bookings(id) on delete cascade,
  channel text not null default 'whatsapp',
  event_type text not null,
  recipient text not null,
  message text not null,
  status text not null default 'pending',
  provider_response jsonb,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create or replace function public.booking_capacity()
returns integer
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((value->>'max_parallel_bookings')::integer, 3)
  from public.site_settings
  where key = 'booking'
  union all
  select 3
  limit 1;
$$;

create or replace function public.booking_price_for_duration(p_duration_minutes integer)
returns numeric
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  configured_price numeric;
begin
  select price
  into configured_price
  from public.booking_duration_prices
  where duration_minutes = p_duration_minutes
    and is_active = true;

  if configured_price is null then
    raise exception 'Duracion de reserva no disponible';
  end if;

  return configured_price;
end;
$$;

create or replace function public.set_booking_derived_fields()
returns trigger
language plpgsql
as $$
begin
  new.ends_at = new.starts_at + make_interval(mins => new.duration_minutes);
  new.total_amount = public.booking_price_for_duration(new.duration_minutes);

  if new.payment_type = 'deposit_50' then
    new.amount_due = round(new.total_amount * 0.5, 2);
  else
    new.amount_due = new.total_amount;
  end if;

  if new.change_expires_at is null then
    new.change_expires_at = date_trunc('day', new.starts_at at time zone 'America/La_Paz')
      at time zone 'America/La_Paz' + interval '1 day';
  end if;

  return new;
end;
$$;

drop trigger if exists set_booking_derived_fields on public.bookings;
create trigger set_booking_derived_fields
before insert or update of starts_at, duration_minutes, total_amount, payment_type
on public.bookings
for each row execute function public.set_booking_derived_fields();

create or replace function public.ensure_booking_slot_available()
returns trigger
language plpgsql
as $$
declare
  overlapping_count integer;
  max_capacity integer;
  slot_weekday integer;
  slot_time time;
  slot_end_time time;
begin
  new.ends_at = new.starts_at + make_interval(mins => new.duration_minutes);

  if new.status not in ('pending_payment', 'confirmed') then
    return new;
  end if;

  slot_weekday = extract(dow from new.starts_at at time zone 'America/La_Paz');
  slot_time = (new.starts_at at time zone 'America/La_Paz')::time;
  slot_end_time = (new.ends_at at time zone 'America/La_Paz')::time;

  if not exists (
    select 1
    from public.booking_availability_rules rule
    where rule.weekday = slot_weekday
      and rule.is_open = true
      and slot_time >= rule.opens_at
      and slot_end_time <= rule.closes_at
  ) then
    raise exception 'Horario fuera de atencion';
  end if;

  if exists (
    select 1
    from public.booking_blackouts blackout
    where new.starts_at < blackout.ends_at
      and new.ends_at > blackout.starts_at
  ) then
    raise exception 'Horario bloqueado por administracion';
  end if;

  max_capacity = public.booking_capacity();

  select count(*)
  into overlapping_count
  from public.bookings booking
  where booking.id <> new.id
    and booking.status in ('pending_payment', 'confirmed')
    and (booking.status = 'confirmed' or booking.expires_at > now())
    and new.starts_at < booking.ends_at
    and new.ends_at > booking.starts_at;

  if overlapping_count >= max_capacity then
    raise exception 'Horario sin cupos disponibles';
  end if;

  return new;
end;
$$;

drop trigger if exists ensure_booking_slot_available on public.bookings;
create trigger ensure_booking_slot_available
before insert or update of starts_at, duration_minutes, status
on public.bookings
for each row execute function public.ensure_booking_slot_available();

create or replace function public.enqueue_booking_notification()
returns trigger
language plpgsql
as $$
declare
  message text;
begin
  if tg_op = 'INSERT' then
    message = 'Gracias por reservar en Eureka. Tu codigo de reserva es ' || new.reservation_code ||
      '. Para cambiar tu horario una sola vez, usa este codigo en la pagina.';
  elsif old.status is distinct from new.status and new.status = 'confirmed' then
    message = 'Tu reserva en Eureka fue confirmada. Codigo: ' || new.reservation_code ||
      '. Te esperamos el ' || to_char(new.starts_at at time zone 'America/La_Paz', 'DD/MM/YYYY HH24:MI') || '.';
  elsif old.status is distinct from new.status and new.status = 'rejected' then
    message = 'Tu reserva en Eureka no pudo ser verificada. El horario se liberara si no confirmas el pago nuevamente.';
  elsif old.starts_at is distinct from new.starts_at then
    message = 'Tu reserva en Eureka fue cambiada. Nuevo horario: ' ||
      to_char(new.starts_at at time zone 'America/La_Paz', 'DD/MM/YYYY HH24:MI') ||
      '. Codigo: ' || new.reservation_code || '.';
  else
    return new;
  end if;

  insert into public.notification_events (booking_id, event_type, recipient, message)
  values (new.id, lower(tg_op) || '_booking', new.phone, message);

  return new;
end;
$$;

drop trigger if exists enqueue_booking_notification on public.bookings;
create trigger enqueue_booking_notification
after insert or update of status, starts_at
on public.bookings
for each row execute function public.enqueue_booking_notification();

create or replace function public.create_public_booking(
  p_full_name text,
  p_phone text,
  p_national_id text,
  p_starts_at timestamptz,
  p_duration_minutes integer,
  p_payment_type public.payment_amount_type,
  p_payment_qr_id uuid default null,
  p_party_size integer default 1,
  p_payment_reference text default null,
  p_payment_receipt_path text default null
)
returns table (
  booking_id uuid,
  reservation_code text,
  amount_due numeric,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_booking public.bookings;
begin
  insert into public.bookings (
    full_name,
    phone,
    national_id,
    starts_at,
    duration_minutes,
    payment_type,
    payment_qr_id,
    party_size,
    payment_reference,
    payment_receipt_path
  )
  values (
    trim(p_full_name),
    trim(p_phone),
    trim(p_national_id),
    p_starts_at,
    p_duration_minutes,
    p_payment_type,
    p_payment_qr_id,
    p_party_size,
    nullif(trim(coalesce(p_payment_reference, '')), ''),
    nullif(trim(coalesce(p_payment_receipt_path, '')), '')
  )
  returning * into inserted_booking;

  return query
  select
    inserted_booking.id,
    inserted_booking.reservation_code,
    inserted_booking.amount_due,
    inserted_booking.expires_at;
end;
$$;

create or replace function public.reschedule_booking_once(
  p_reservation_code text,
  p_phone text,
  p_starts_at timestamptz,
  p_duration_minutes integer
)
returns table (
  booking_id uuid,
  reservation_code text,
  starts_at timestamptz,
  ends_at timestamptz,
  status public.booking_status
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_booking public.bookings;
begin
  select *
  into target_booking
  from public.bookings booking
  where booking.reservation_code = upper(trim(p_reservation_code))
    and booking.phone = trim(p_phone)
    and booking.status in ('pending_payment', 'confirmed')
  for update;

  if target_booking.id is null then
    raise exception 'Reserva no encontrada';
  end if;

  if target_booking.change_used then
    raise exception 'El cambio de horario ya fue utilizado';
  end if;

  if now() > target_booking.change_expires_at then
    raise exception 'El codigo de cambio ya expiro';
  end if;

  update public.bookings
  set starts_at = p_starts_at,
      duration_minutes = p_duration_minutes,
      status = 'pending_payment',
      change_used = true,
      expires_at = now() + interval '10 minutes',
      confirmed_at = null,
      rejected_at = null
  where id = target_booking.id
  returning * into target_booking;

  return query
  select
    target_booking.id,
    target_booking.reservation_code,
    target_booking.starts_at,
    target_booking.ends_at,
    target_booking.status;
end;
$$;

create or replace function public.expire_pending_bookings()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_count integer;
begin
  update public.bookings
  set status = 'expired'
  where status = 'pending_payment'
    and expires_at <= now();

  get diagnostics affected_count = row_count;
  return affected_count;
end;
$$;

create or replace view public.public_booking_slots as
select
  starts_at,
  ends_at,
  count(*) filter (
    where status = 'confirmed'
      or (status = 'pending_payment' and expires_at > now())
  ) as used_capacity,
  public.booking_capacity() as max_capacity
from public.bookings
where status in ('pending_payment', 'confirmed')
group by starts_at, ends_at;

alter table public.admin_profiles enable row level security;
alter table public.contacts enable row level security;
alter table public.site_settings enable row level security;
alter table public.booking_duration_prices enable row level security;
alter table public.hero_slides enable row level security;
alter table public.novelty_items enable row level security;
alter table public.pedidosya_promos enable row level security;
alter table public.payment_qrs enable row level security;
alter table public.booking_availability_rules enable row level security;
alter table public.booking_blackouts enable row level security;
alter table public.bookings enable row level security;
alter table public.notification_events enable row level security;

drop policy if exists "Admins can manage admin profiles" on public.admin_profiles;
create policy "Admins can manage admin profiles"
on public.admin_profiles
for all
to authenticated
using (public.is_owner_admin())
with check (public.is_owner_admin());

drop policy if exists "Admins can manage contacts" on public.contacts;
create policy "Admins can manage contacts"
on public.contacts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can insert contacts" on public.contacts;
create policy "Public can insert contacts"
on public.contacts
for insert
to anon, authenticated
with check (deleted = false);

drop policy if exists "Public can read public settings" on public.site_settings;
create policy "Public can read public settings"
on public.site_settings
for select
to anon, authenticated
using (is_public = true);

drop policy if exists "Admins can manage settings" on public.site_settings;
create policy "Admins can manage settings"
on public.site_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active duration prices" on public.booking_duration_prices;
create policy "Public can read active duration prices"
on public.booking_duration_prices
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Admins can manage duration prices" on public.booking_duration_prices;
create policy "Admins can manage duration prices"
on public.booking_duration_prices
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active hero slides" on public.hero_slides;
create policy "Public can read active hero slides"
on public.hero_slides
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Admins can manage hero slides" on public.hero_slides;
create policy "Admins can manage hero slides"
on public.hero_slides
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active novelty items" on public.novelty_items;
create policy "Public can read active novelty items"
on public.novelty_items
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Admins can manage novelty items" on public.novelty_items;
create policy "Admins can manage novelty items"
on public.novelty_items
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active pedidosya promos" on public.pedidosya_promos;
create policy "Public can read active pedidosya promos"
on public.pedidosya_promos
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Admins can manage pedidosya promos" on public.pedidosya_promos;
create policy "Admins can manage pedidosya promos"
on public.pedidosya_promos
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active payment qrs" on public.payment_qrs;
create policy "Public can read active payment qrs"
on public.payment_qrs
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Admins can manage payment qrs" on public.payment_qrs;
create policy "Admins can manage payment qrs"
on public.payment_qrs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read availability rules" on public.booking_availability_rules;
create policy "Public can read availability rules"
on public.booking_availability_rules
for select
to anon, authenticated
using (is_open = true);

drop policy if exists "Admins can manage availability rules" on public.booking_availability_rules;
create policy "Admins can manage availability rules"
on public.booking_availability_rules
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage blackouts" on public.booking_blackouts;
create policy "Admins can manage blackouts"
on public.booking_blackouts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage bookings" on public.bookings;
create policy "Admins can manage bookings"
on public.bookings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage notification events" on public.notification_events;
create policy "Admins can manage notification events"
on public.notification_events
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant execute on function public.create_public_booking(
  text,
  text,
  text,
  timestamptz,
  integer,
  public.payment_amount_type,
  uuid,
  integer,
  text,
  text
) to anon, authenticated;

grant execute on function public.reschedule_booking_once(text, text, timestamptz, integer)
to anon, authenticated;

grant execute on function public.expire_pending_bookings()
to anon, authenticated;

insert into public.site_settings (key, value, is_public)
values
  ('booking', '{"max_parallel_bookings": 3, "pending_payment_minutes": 10}'::jsonb, true),
  ('landing', '{"hero_title": "EUREKA convierte una tarde normal en planazo", "hero_cta": "Registrar score"}'::jsonb, true)
on conflict (key) do nothing;

insert into public.booking_duration_prices (label, duration_minutes, price, sort_order, is_active)
values
  ('30 minutos', 30, 50, 1, true),
  ('1 hora', 60, 100, 2, true)
on conflict (duration_minutes) do update
set label = excluded.label,
    price = excluded.price,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active;

insert into public.hero_slides (image_path, alt_text, sort_order)
values
  ('/image/hero/hero1.webp', 'Minigolf Eureka', 1),
  ('/image/hero/hero2.webp', 'Ambiente Eureka', 2),
  ('/image/hero/hero3.webp', 'Experiencia Eureka', 3),
  ('/image/hero/hero4.webp', 'Juegos en Eureka', 4),
  ('/image/hero/hero5.webp', 'Salida en Eureka', 5)
on conflict do nothing;

insert into public.novelty_items (title, description, price, image_path, badge, sort_order, is_featured)
values
  ('Oktoberfest', 'Promos de temporada para acompanar una ronda con amigos.', null, '/image/novedades/novedad1.png', 'Promo destacada', 1, true),
  ('Cheesecake de fresas', 'Un postre mas vistoso y antojable para redondear la visita.', null, '/image/novedades/novedad2.png', 'Favorito del mes', 2, false),
  ('Galletas de la casa', 'Detalle casero para sumar algo rico mientras disfrutas el lugar.', null, '/image/novedades/novedad3.png', 'Recien horneado', 3, false)
on conflict do nothing;

insert into public.pedidosya_promos (title, description, image_path, cta_url, points, is_active)
values (
  'Si el plan sigue en casa, el sabor tambien',
  'Postres y antojos listos para seguir el plan sin salir.',
  '/image/novedades/novedad2.png',
  'https://www.pedidosya.com.bo/restaurantes/cochabamba/eureka-cbba-cbf01504-3f94-450c-9c8c-38cbaff401bf-menu',
  array['Pedido rapido', 'Visual mas limpio', 'CTA mas visible'],
  true
)
on conflict do nothing;

insert into public.booking_availability_rules (weekday, opens_at, closes_at, is_open)
values
  (0, '14:00', '22:00', true),
  (1, '14:00', '22:00', true),
  (2, '14:00', '22:00', true),
  (3, '14:00', '22:00', true),
  (4, '14:00', '22:00', true),
  (5, '14:00', '23:00', true),
  (6, '14:00', '23:00', true)
on conflict (weekday) do nothing;

insert into storage.buckets (id, name, public)
values
  ('hero', 'hero', true),
  ('novedades', 'novedades', true),
  ('payments', 'payments', true),
  ('qr', 'qr', true)
on conflict (id) do nothing;

drop policy if exists "Public can read Eureka media" on storage.objects;
create policy "Public can read Eureka media"
on storage.objects
for select
to anon, authenticated
using (bucket_id in ('hero', 'novedades', 'payments', 'qr'));

drop policy if exists "Admins can manage Eureka media" on storage.objects;
create policy "Admins can manage Eureka media"
on storage.objects
for all
to authenticated
using (bucket_id in ('hero', 'novedades', 'payments', 'qr') and public.is_admin())
with check (bucket_id in ('hero', 'novedades', 'payments', 'qr') and public.is_admin());
